#!/bin/bash

#	@title: Sybil
#	@description: A utility for opening and closing a LUKS device with a yubi key

##	strict mode
set -euo pipefail
IFS=$'\n\t'

DIR="$(dirname $(readlink -f $0))"

case $1 in
	"status")
		$DIR/is_mounted.sh
		;;
	"env")
		$DIR/fyle=dump_vars.sh
		;;
	"mount")
		sudo $DIR/mount.sh
		;;
	"dismount")
		sudo $DIR/dismount.sh
		;;
	"diary")
		$DIR/new_entry.sh
		;;
	"yubi")
		$DIR/yubikey_info.sh
		;;
	"help")
		cat $0
		;;
	*)
		echo "unknown command"
		exit 5;
		;;
esac

exit 0;
