name: sybil
base: core18
version: 'v0.0.3'
summary: Manage LUKS-encryped devices or folders with a Yubikey
description: |
  Sybil allows you to enroll one or more yubikeys to authenticate a LUKS-encryped device.
  It does so by saving a randomly-generated challenge to disk,
  and the resultant HMAC challenge to a slot in the LUKS device.
type: app
grade: devel
confinement: devmode # use 'strict' once you have the right plugs and slots

apps:
  sybil:
    command: opt/fukt/sybil/sybil
    plugs:
      - hidraw

parts:
  sybil:
    build-environment:
      - LANG: C.UTF-8
      - LC_ALL: C.UTF-8
    plugin: dump
    source: source
    organize:
      "scripts": "/opt/fukt/sybil"
    build-packages:
      - locales-all
    stage-packages:
      - yubikey-personalization

